data:
    type: "TrainTestDtuDataset"
    train_dataset: "train.txt"
    val_dataset: "test.txt"
    patch_size: 256
    channels: 3
    num_workers: 4
    root_dir: "/root/autodl-tmp/mvs_training/dtu/"
    split: "/root/autodl-tmp/project/dp_simple/CasMVSNet_pl/datasets/lists/dtu/"
    ckpt_dir: "/root/autodl-tmp/Diffusion/ckpt/depth/"
    conditional: True
    split_path: "/root/autodl-tmp/project/dp_simple/CasMVSNet_pl/datasets/lists/dtu"

model:
    use_depth: True
    decoder_only: False
    use_lora: True 
    hfrm_ranks: 1
    attn_ranks: 1
    in_channels: 3
    out_ch: 3
    ch: 64
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    use_cross_frame: True 
    num_input_view: 3
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True
logger:
    exp_name: "without_depth"
    logger_path: "/root/tf-logs"
diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 200

training:
    batch_size: 6
    n_epochs: 500
    validation_freq: 1000

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0001
    amsgrad: False
    eps: 0.00000001
    step_size: 50
    gamma: 0.8
