data:
    # type: "TrainTestDtuDataset"
    # train_dataset: "train.txt"
    # val_dataset: "test.txt"
    # patch_size: 256
    # channels: 3
    # num_workers: 4
    # root_dir: "/root/autodl-tmp/mvs_training/dtu/Rectified"
    # split: "/root/autodl-tmp/mvs_training/dtu/"
    # ckpt_dir: "/root/autodl-tmp/Diffusion/ckpt/lora_version"
    # conditional: True
    # split_path: "/root/autodl-tmp/project/dp_simple/CasMVSNet_pl/datasets/lists/"
    type: "dtu2" #"DTUDataset"
    train_dataset: "train.txt"
    val_dataset: "test.txt"
    single_frame: False
    patch_size: 256
    channels: 3
    num_workers: 4
    root_dir: "/openbayes/input/input0/mvs_training/dtu/"
    split: "/root/autodl-tmp/project/dp_simple/CasMVSNet_pl/datasets/lists/dtu/"
    ckpt_dir: "/root/autodl-tmp/Diffusion/ckpt/lora_single_frame_decoder/"
    conditional: True
    split_path: "/root/autodl-tmp/project/dp_simple/CasMVSNet_pl/datasets/lists/dtu"

model:
    feature_extract: True
    use_depth: True
    
    use_lora: False
    training_mode: "only_mvs"
    
    not_train_diffusion: True 
    hfrm_ranks: 1
    attn_ranks: 1
    in_channels: 3
    only_mvs: True

    out_ch: 3
    ch: 64
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    use_cross_frame: True 
    num_input_view: 3
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True
logger:
    exp_name: "use_trained_extraction_depth_refine_zero_init"
    logger_path: "/openbayes/home/tf_dir"
diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 200
device: 'cuda'
training:
    batch_size: 4
    n_epochs: 50
    validation_freq: 1000

type:
    weight_decay: 0.000
    num_epochs: 10
    decay_gamma: 0.4
    optimizer: "adam"
    lr: 0.0001
    amsgrad: False
    eps: 0.00000001
    step_size: 50
    gamma: 0.8
    use_amp: True
    lr_scheduler : 'cosine'
    decay_step: 2000
    warmup_epochs: 0

